### ISSUE TITLE
Can't specify options to Faye (eg, use the permessage-deflate extension)

### ISSUE THREAD

**Issue by glasser** [sockjs/sockjs-node#170]
Faye recently added support for the WebSocket permessage-deflate extension. I'd like to be able to use it in a SockJS server.  My planned interface is just to add a fayeServerOptions option to createServer which is passed directly to the FayeWebSocket constructor.  Will probably create a release with these changes in the next few days.

**Comment by mikalai-ramashka** [comment]
Hey guys, how can i use it with sockjs server? Do you have example?

**Comment by Maksims** [comment]
Same here, what is the way to enable permessage-deflate with sockjs?
Lack of documentation on this is upsetting :(

**Comment by brycekahle** [comment]
If you look at the commit, you specify a `faye_server_options` key to the `options` you pass into the `createServer` function.

**Comment by Maksims** [comment]
Figured it out:
```javascript
var deflate = require('permessage-deflate');

var socket = sockjs.createServer({
    faye_server_options: {
        extensions: [
            deflate
        ]
    }
});
```
