### ISSUE TITLE
Always growing FD count

### ISSUE THREAD

**Issue by miwojs** [sockjs/sockjs-node#171]
Hello, i upgrade from 0.3.9 to 0.3.12 and problem raise up. FD growing up and when i see graph with http connections, they still going to up.  Num of connections i get from:

server = http.createServer(express);
console.log(server._connections); 

and result is here: http://grabberapp.com/ety45t (with 6000 users). FD count in version 0.3.9 was about 1 to 1 with online users (~6000 FD). In version 0.3.12 FD going up (last value was ~50000 and then i need restart server - max open files = 50000).

How many FD should by opened, when you have e.g. 10000 ESTABLISHED connections.
When i go down to version 0.3.9 FD ~ ESTABLISHED connections. In version 0.3.12 after few hours is 3-times greater and still go up.

**Comment by brycekahle** [comment]
Do you know what transport it is using primarily? That would help in tracking down the issue.

**Comment by 3rd-Eden** [comment]
The major difference is of course the faye-websocket version which received a major update to handle deflate.

**Comment by 3rd-Eden** [comment]
See https://github.com/faye/faye-websocket-node/issues/38

**Comment by renatoc** [comment]
+1

**Comment by brycekahle** [comment]
Waiting for faye-websocket-node fix.

**Comment by lpinca** [comment]
`faye-websocket@0.9.3` is out with a fix for the issue linked above.

**Comment by brycekahle** [comment]
published to npm as `0.3.13`

**Comment by 3rd-Eden** [comment]
Awesome *high five*
