### ISSUE TITLE
Serialize connection object to string then back

### ISSUE THREAD

**Issue by RoThePro** [sockjs/sockjs-node#173]
Is there any module or something that can serialize a connection object into a string to store in a database and then back to a connection? Thank you

**Comment by brycekahle** [comment]
What exactly are you trying to accomplish? The primary part of a connection is a file descriptor which is machine specific and cannot be serialized.

**Comment by RoThePro** [comment]
I'm trying to make a single node chat server, and store the connections in a redis database so as to be more performant than an associative array.

**Comment by majek** [comment]
Sticky sessions are supported by sockjs, no need for redis.

**Comment by RoThePro** [comment]
What are sticky sessions?
