### ISSUE TITLE
Cannot find module './lib/sockjs'

### ISSUE THREAD

**Issue by martinkarlsson** [sockjs/sockjs-node#174]
There is no "sockjs.js" in directory lib, just a placeholder. How I am supposed to implement the sockjs node server? Unfortunately I cannot install with npm as our firewall does not allow the communication needed.

**Comment by 3rd-Eden** [comment]
That's because of all the horrible coffeescript that this project is using. It's compiled in to the lib folder before they publish a version to npm. You could ofcourse checkout this git repostory, install all dependencies and devDependencies and run the compile step your self.

**Comment by brycekahle** [comment]
If you can't use npm at all, you will need to do exactly what @3rd-Eden said.
