### ISSUE TITLE
CORS with IDN domains IE11

### ISSUE THREAD

**Issue by perlexed** [sockjs/sockjs-node#176]
IE11 (at least) doesn't match domain in the 'Access-Control-Allow-Origin' response header when the domain name is an Internationalized Domain Name (e.g. [http://тест.рф](http://тест.рф)).

To solve this issue we made local changes to the xhr_cors function in /lib/trans-xhr.js, as following:

```
xhr_cors: function(req, res, content) {
  var headers, origin;
  if (
    !req.headers['origin'] || req.headers['origin'] === 'null'
    || (req.headers['user-agent'] && isIE(req.headers['user-agent']) && !isOriginNonI18n(req.headers['origin']))
  ) {
  ...
```

Where 'isIE' and 'isOriginNonI18n' are function that return corresponding regexp test result.

Hope to get rid of local changes in favor of your library update with this issue fix.

**Comment by brycekahle** [comment]
Can you post an example HTTP request/response? Thanks.

**Comment by perlexed** [comment]
Request headers:
Request    GET /v1.8-51/comet/10/info HTTP/1.1
Accept    */*
Referer    http://мудрыедети.рф/shop/
<http://xn--d1aacbpt3atd6f.xn--p1ai/shop/>
Accept-Language    ru-RU
Origin    http://мудрыедети.рф <http://xn--d1aacbpt3atd6f.xn--p1ai>
Accept-Encoding    gzip, deflate
User-Agent    Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)
like Gecko
Host    traffic8.helponclick.com
DNT    1
Connection    Keep-Alive
Cache-Control    no-cache

Response headers:
Response    HTTP/1.1 200 OK
Date    Wed, 18 Mar 2015 20:11:59 GMT
Content-Type    application/json; charset=UTF-8
Transfer-Encoding    chunked
Connection    keep-alive
Set-Cookie    __cfduid=dd296cbf87f16836627a7bff64665248a1426709519;
expires=Thu, 17-Mar-16 20:11:59 GMT; path=/; domain=.helponclick.com;
HttpOnly
Access-Control-Allow-Credentials    true
Access-Control-Allow-Origin    http://мудрыедети.рф
<http://xn--d1aacbpt3atd6f.xn--p1ai>
Vary    Origin
Cache-Control    no-store, no-cache, must-revalidate, max-age=0
Server    cloudflare-nginx
CF-RAY    1c93970092a40a4e-ARN

2015-03-18 23:36 GMT+07:00 Bryce Kahle <notifications@github.com>:

**Comment by brycekahle** [comment]
Looks like it might be sending the punycode version too. Perhaps it is expecting that in the response?

**Comment by perlexed** [comment]
I think I'm out of the context now. What might be sending the punycode
version?

2015-05-30 10:38 GMT+07:00 Bryce Kahle <notifications@github.com>:

**Comment by brycekahle** [comment]
IE11 is sending a punycode version of the Origin according to the request/response trace you sent:
`Origin    http://мудрыедети.рф <http://xn--d1aacbpt3atd6f.xn--p1ai>`

**Comment by brycekahle** [comment]
How did you capture that request/response trace? I've done some research and only ASCII characters should be sent in HTTP headers, so it should be in punycode form. I see both versions in your trace, so I wonder if you captured using a tool that was decoding the punycode.

**Comment by perlexed** [comment]
It was copied from the Internet Explorer 11 console, from a detailed
request/response on Network tab.

2015-07-22 12:49 GMT+07:00 Bryce Kahle <notifications@github.com>:

**Comment by brycekahle** [comment]
According to this, it was a bug in IE10/11/Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8075637/
