### ISSUE TITLE
Intent to transition away from coffeescript

### ISSUE THREAD

**Issue by brycekahle** [sockjs/sockjs-node#178]
I don't think coffeescript is providing any value to this library at this point. It has actually caused bugs because of some of syntax. I also think it is a barrier to a greater pool of potential contributors.

I wouldn't just run the compiler and commit the output immediately. Some cleanup will be necessary in order to ensure the code is clean.

I'd like to know what everyone thinks about this.

**Comment by Slayer95** [comment]
+1

The opportunity could be used to turn towards ES6, which has some features that CS intends to provide. Babel could be relied upon to keep support of Node/io.js versions with old V8.

**Comment by mathieumg** [comment]
> The opportunity could be used to turn towards ES6, which has some features that CS intends to provide. Babel could be relied upon to keep support of Node/io.js versions with old V8.

+1 to the issue and to that approach :+1:

**Comment by brycekahle** [comment]
I love Babel, but I'm not sure I want to trade one preprocessor for another. I really enjoy ES6, but I think I would wait to utilize ES6 until support lands in Node without special flags.

**Comment by lucidrains** [comment]
I would be happy to rewrite it to ES6

**Comment by mathieumg** [comment]
Relevant: https://github.com/eventualbuddha/decaffeinate

**Comment by erickponce** [comment]
I vote for a rewrite in TypeScript, but I will be happy with pure JavaScript to :)

**Comment by SpaceK33z** [comment]
This week I contributed something to sockjs-node, and I can confirm that Coffeescript initially scared me and made contributing a lot harder. My suggestion would be to just use Javascript, without a preprocessor.

**Comment by awill2** [comment]
+1 for Typescript or pure html.

**Comment by brycekahle** [comment]
Coffeescript removed as of b991a1d948772f9015214590fcb881da10fc5153
