### ISSUE TITLE
Documentation and examples out of date

### ISSUE THREAD

**Issue by NullDivision** [sockjs/sockjs-node#182]
I noticed that both the example and the documentation is out of date. 0.3.4 was a long time ago.

Could we possibly get an update on that?

**Comment by brycekahle** [comment]
Did you notice specific things that were out of date?

**Comment by NullDivision** [comment]
Examples specify 0.3.4 as the current version. I'm guessing this can be integrated into the build script to allow version values to persist to the example files.

I was also looking for how to set information in the `/info` route. I noticed that this has been added in a more recent version (according to the changelog) but I can't find any documentation for it short of looking at tag diffs.

**Comment by brycekahle** [comment]
I can try and update those soon, but I would also welcome a pull request if you are in a hurry.
