### ISSUE TITLE
top level websocket url available when websocket option set to false

### ISSUE THREAD

**Issue by tmds** [sockjs/sockjs-node#183]
The session websocket url returns [404](https://github.com/sockjs/sockjs-node/blob/d4385b584682c5f0ae8ccb082678f4fbea90f7c7/src/sockjs.coffee#L103) when the websocket option is set to false.
The top level websocket url is [always available](https://github.com/sockjs/sockjs-node/blob/d4385b584682c5f0ae8ccb082678f4fbea90f7c7/src/sockjs.coffee#L85).

I expected the top level websocket url to also return 404 when websocket is set to false. Is this an oversight or is this behavior intentional?

**Comment by brycekahle** [comment]
Probably an oversight. I can fix it quickly.

**Comment by brycekahle** [comment]
Thanks for the bug report!
