### ISSUE TITLE
private chat using sockjs

### ISSUE THREAD

**Issue by abhinav76** [sockjs/sockjs-node#186]
I am new to sockets and sockjs. So I am trying to build a chat application using nodejs and angularjs and sockjs. I have made a simple chat application using  sockjs, what I want is to make the chat private between two users. Now if A want to send message to B and C wants to send message to B, then there must be something with which A cannot see the messages sent by C and vice-versa,like the orivate rooms between any two users. Can you guide me how to achieve that?

**Comment by brycekahle** [comment]
Check out https://github.com/sockjs/websocket-multiplex/
