### ISSUE TITLE
Frequent connection closure in sockjs behind nginx

### ISSUE THREAD

**Issue by GauravRachchh** [sockjs/sockjs-node#194]
We are using sockjs v1.0.0 library on client and spring 4.1 on server. It uses xhr polling as transport protocol. When sockjs server is behind nginx ,we observe  frequent connection closure in console log on client side.

lib.js:339_ws_onclose. wasClean: false code: 1006 reason: Server lost session
lib.js:339 _ws_onclose. wasClean: false code: 1006 reason: Server lost session
lib.js:339 _ws_onclose. wasClean: false code: 1006 reason: Sending error: Error: http status 0
lib.js:339 _ws_onclose. wasClean: false code: 1006 reason: Server lost session
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 2000 reason: All transports failed
lib.js:339 _ws_onclose. wasClean: false code: 1002 reason: Cannot connect to server

**Comment by brycekahle** [comment]
Since you are not using the node server, this is the wrong place for this issue.
