### ISSUE TITLE
Sticky Session with single SockJS server (howto)

### ISSUE THREAD

**Issue by charyorde** [sockjs/sockjs-node#195]
I'll like to know how to retrieve an existing SockJS Connection with sticky session turned on. How's this
possible within the body of the SockJS Connection instance?

```
var echo = sockjs.createServer({ sockjs_url: 'http://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js' });
echo.on('connection', function(conn) {
    // if we can't serialize conn for reuse, how can I leverage sticky session here
    conn.on('data', function(message) {
        conn.write(message);
    });
    conn.on('close', function() {});
});
```

I appreciate your help. Thanks

**Comment by syberkitten** [comment]
My understanding is that sticky session is something that is enforced on a lower level, thus load balancer or a reverse-proxy which uses the JSESSIONID cookie a token to "stick" you to the previous connected server.

> JSESSIONID cookie sticky sessions. By default SockJS server sets this cookie. Some load balancers understand that cookie and enable session stickyness (for example this is the case for CloudFoundry).

from an article about socks: 
https://github.com/sockjs/sockjs-client/wiki/%5BArticle%5D-SockJS:-WebSocket-emulation-done-right

hope this helps....
