### ISSUE TITLE
Unable to consume the messages using SockJS client

### ISSUE THREAD

**Issue by darshanmehta10** [sockjs/sockjs-node#196]
I am using the below script to connect to RabbitMQ and read the messages

    var sock;
    var stomp;
    var messageCount = 0;
    var stompConnect = function() {
	
    sock = new SockJS(options.url);

	stomp = Stomp.over(sock);
	stomp.connect({}, function(frame) {
		debug('Connected: ', frame);
		console.log(frame);
		
		var id = stomp.subscribe('<url>' + options.source + "." + options.type + "." + options.id, function(d) {
			console.log(messageCount);
			messageCount = messageCount + 1;
		}, {'auto-delete' : false, 'x-queue-name' : 'test_name', ack : 'client'});
	}, function(err) {
		console.log(err);
		debug('error', err, err.stack);
		setTimeout(stompConnect, 10);
	});
    };

When I connect for the first time, connection gets established successfully, I am able to see the messageCount increasing.

Now, when I stop the script, the queue does not get deleted (due to `'auto-delete' : false` header), I then try again to connect to the same queue (with around 1000 messages). It gets connected to the queue, however it is not able to read any messages. Besides, I can see multiple instances (every 10 second, due to timeout thing perhaps) the following in the logs:

`Whoops! Lost connection to <url>`

I then tried by removing `'ack'` header, in this case, it was able to connect to the same queue successfully, as there was no ack header, server drained out all the messages but none reached to the client (I was able to receive the new messages though).

When there are around 200 messages in the queue, reconnect attempt is able to stream all the queued messages. However, if the count increases, it either loses the messages or goes into infinite connection loop. Do we need to specify prefetch size of anything?

**Comment by brycekahle** [comment]
This repo is for the SockJS node server. This appears to be an issue with Stomp or sockjs-client?
