### ISSUE TITLE
Allow configuring which connection headers are exposed

### ISSUE THREAD

**Issue by mitar** [sockjs/sockjs-node#198]
Currently, there is a hard-coded list of headers which are available on the connection. I think this should be configurable. Or at least all `x-` prefixed headers should be available.

I am trying to use Meteor with [Sandstorm](http://sandstorm.io/) and the latter sends quite some information in proxied requests in headers with `x-` prefix. Currently all that is not accessible. :-(

**Comment by prawnsalad** [comment]
I also need this as I'm trying to read cookies and custom headers. What is the rational for having a whitelist of cookies?

**Comment by mitar** [comment]
You can read here about cookies: https://github.com/sockjs/sockjs-node#authorisation

**Comment by mitar** [comment]
I made #202.

**Comment by kentonv** [comment]
The problem with cookies also applies to the `X-Sandstorm` headers. The fact that they are added server-side by a reverse proxy does not make them any more trustworthy than cookies. In fact, the proxy derives these headers from a cookie. You should not whitelist them.
