### ISSUE TITLE
New patch release?

### ISSUE THREAD

**Issue by SpaceK33z** [sockjs/sockjs-node#214]
I would really appreciate it if there could be a new patch release now that #213 is merged. It doesn't seem like the other open PRs are going to be merged, so it can take a long time for the next release.

By the way, after this release, sockjs-node is compatible with http/2 implementations :).

**Comment by SpaceK33z** [comment]
Pretty please :)? We're waiting on this to rollout http/2 for webpack-dev-server.

**Comment by brycekahle** [comment]
`0.3.18` just published.

**Comment by SpaceK33z** [comment]
Thank you!
