### ISSUE TITLE
Iframe fallback refers to old version of SockJS-Client

### ISSUE THREAD

**Issue by holloway** [sockjs/sockjs-node#222]
I'm not sure if this is a bug or not, but on [line 146 of `sockjs.coffee`](https://github.com/sockjs/sockjs-node/blob/master/src/sockjs.coffee#L146) there's a URL specified that's an old version of the SockJS-Client.

Should this be upgraded, or should users wanting a newer version just override the `sockjs_url` option?

fyi It's causing [a bug in `create-react-app`](https://github.com/facebookincubator/create-react-app/issues/1268).

**Comment by brycekahle** [comment]
We should probably update it to be the latest in 1 `https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js`

**Comment by raybooysen** [comment]
A new user of sock-js but why is the CDN URL included at all?

**Comment by brycekahle** [comment]
@raybooysen Please read the documentation before asking questions: https://github.com/sockjs/sockjs-node#server-class

**Comment by raybooysen** [comment]
Hi @brycekahle, I have read the documentation, but this is more a discussion about why it is included at all.  The documentation says:
```
This iframe also does need to load SockJS javascript client library, and this option lets you specify its url (if you're unsure, point it to the latest minified SockJS client release, this is the default)
```
It would seem prudent to make it required instead of falling back to something that needs to make a call across the internet, and removes the class of bugs around out of date CDN URLs.

**Comment by brycekahle** [comment]
https://github.com/sockjs/sockjs-node/commit/e6eeb42949f7f780daad872f4a34ad62b2ffa6a7 updated the URL to be the latest 1.x release of sockjs-client. Closing this issue.
