### ISSUE TITLE
Close/terminate/kill server listening

### ISSUE THREAD

**Issue by Josema** [sockjs/sockjs-node#225]
Probably is already asked, but I couldn't find it here or in sockjs-client documentation either.

Is there any way to close the server to stop listening. For testing, I need to stop the server and the process. I tried closing all the clients one by one, but the server still listening and the process never ends up.

**Comment by brycekahle** [comment]
Use the core [`close()`](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_server_close_callback) function on the `http.Server`.
