### ISSUE TITLE
uWebsockets support, anyone interested or can develop?

### ISSUE THREAD

**Issue by shimondoodkin** [sockjs/sockjs-node#226]
seems recently uWebsockets is popular because of performance.
is it possible to switch use uWebsockets?  , will it be better?

**Comment by dceejay** [comment]
maybe a variation of this patch https://gist.github.com/danielstjules/71ade40ce7c145c857a6

**Comment by brycekahle** [comment]
`uWebsockets` is a C++ library. This makes installing the package a lot more complicated and breaks a lot of users in my experience. You would also needs bindings to Node.js, which will definitely result in a loss of performance. I'm not sure the gain would be worth the effort and complexity that comes with a C++ package.

**Comment by Kamil93** [comment]
It definitely shouldn't be closed. I've switched to engine.io with uWS in my stress test app, and it performed over 3 times bettter. It hasn't to be default engine (uws) it can be an option like in engine.io

**Comment by brycekahle** [comment]
I'm not interested in adding uWS as an option. If you want it, feel free to fork and implement.
