### ISSUE TITLE
Slower during load (Angular 4.0)

### ISSUE THREAD

**Issue by gtzinos** [sockjs/sockjs-node#228]
Hello,
I have an app on angular 4.0 which is use your great project during the page load. Everything work fine but it takes 3 seconds on firefox to get your script (/sockjs-node/info?t=1492508290157). Is it an issue of sockjs-node or from webpack ?

**Comment by brycekahle** [comment]
That sounds like a server performance issue which is outside the scope of this library. That endpoint loads very quick locally.
