### ISSUE TITLE
chrome console show error

### ISSUE THREAD

**Issue by imnot2** [sockjs/sockjs-node#230]
```javascript
  Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.4", the iframe: "1.0.1".
```
chrome console show this error,when i using webpack-dev-server plugin 
the sockjs version is 0.3.18

**Comment by shreychaturvedi123** [comment]
any updates on this?

**Comment by brycekahle** [comment]
You need to change the `sockjs_url` parameter when creating the server to match the version you are serving on the front end.
