### ISSUE TITLE
Can I use Sockjs instead of ajax to retrieve page contents?

### ISSUE THREAD

**Issue by awill2** [sockjs/sockjs-node#233]
I'm thinking about use Sockjs to retrieve all the site contents with a JSON.
I have some drawback doing this?
What the max length that a sockjs can handle?
Should I replace my ajax calls to Sockjs or its a bad idea? 
Thank you.

**Comment by brycekahle** [comment]
SockJS does not replace AJAX calls. It even uses them in some cases. I urge you to read up on [WebSockets](https://en.wikipedia.org/wiki/WebSocket) to understand the technology SockJS emulates.
