### ISSUE TITLE
200-300ms Delay after library is loaded to when first xhr call is made to sockjs url 

### ISSUE THREAD

**Issue by mercuryyy** [sockjs/sockjs-node#238]
Trying to fire sockjs as early as possible but there is a delay from when the library finishes and

var sockjs_url = 'url';
sockjs = new SockJS(sockjs_url);

is executed, then comes a 200-300ms delay until the first xhr call is made to the url

i intently fire the lib and code after the onload event is triggered on my pages, is there a delay set somewhere in the lib i cant figure out how to set SockJS() to fire exactly after the lib finished reading.

**Comment by brycekahle** [comment]
Did you intend to file this on the Node.js library?

**Comment by brycekahle** [comment]
This repo is for the Node.js library. You want https://github.com/sockjs/sockjs-client for the browser client.
