### ISSUE TITLE
require('sockjs').createServer(server).attch is undefined

### ISSUE THREAD

**Issue by chnliquan** [sockjs/sockjs-node#245]
use the sockjs-node according to document, the `echo.attach` method is undefined, i can use `echo.installHandlers(server)` to connect the ws

**Comment by brycekahle** [comment]
The master branch does not represent the released version. It can contain changes that have not been released yet. The examples have been updated to reflect some API changes coming in 0.4.0.

**Comment by buzhun** [comment]
when to resolve this problem?

**Comment by brycekahle** [comment]
@buzhun There is no problem. Please read my latest comment.
