### ISSUE TITLE
No matching version found for sockjs@^0.4.0

### ISSUE THREAD

**Issue by DarrenWong** [sockjs/sockjs-node#250]
Try to follow the example to use latest sockjs-node, 
https://github.com/sockjs/sockjs-node/tree/master/examples/echo

`npm install `will get no matching version error, only can install 0.3.19 (my laptop nodejs v8.10.0,npm v6.5.0), but don' t have the attach function 
`echo.attach(server);`
Then i use` npm install https://github.com/sockjs/sockjs-node.git` then a can use the attach function.
Is that the [readme](https://github.com/sockjs/sockjs-node/blob/master/examples/echo/README.md) a little confuse? coz the latest release 0.3.19, not 0.4.0.

**Comment by brycekahle** [comment]
@DarrenWong There is a very clear warning in the README

> ⚠️️ ATTENTION This is pre-release documentation. The documentation for the latest stable release is at: https://github.com/sockjs/sockjs-node/tree/v0.3.19 ️⚠️
