### ISSUE TITLE
Uncaught Error: Incompatible SockJS! Main site uses: "1.3.0", the iframe: "1.4.0".     at VM601 sockjs.min.js:2

### ISSUE THREAD

**Issue by askeralim** [sockjs/sockjs-node#260]
I have tried with vert.x in node.js react application by connecting Vert.x deployed in server,
I am facing following error in browser.
Uncaught Error: Incompatible SockJS! Main site uses: "1.3.0", the iframe: "1.4.0".
    at VM601 sockjs.min.js:2

Also sometimes taking time to get connected, any thoughts

**Comment by brycekahle** [comment]
This error is because your server is configured to use a different version of SockJS than your client is.
