### ISSUE TITLE
please fix security vulnerabilities

### ISSUE THREAD

**Issue by daniel-seitz** [sockjs/sockjs-node#261]
The following files still contain jQuery@1.7.1
- examples\echo\index.html
- examples\express-3.x\index.html
- examples\hapi\html\index.html
- examples\multiplex\index.html

Since this contains a XSS vulnerability, please change to a newer version. See https://snyk.io/vuln/npm:jquery

Although these are just examples, it would be better to have it fixed.

Thank you,
Daniel

**Comment by daniel-seitz** [comment]
Oh just found out that this is a dup of https://github.com/sockjs/sockjs-node/issues/257
The example were added to .npmignore by a previous commit but the build failed. I created a corresponding pr before finding this info https://github.com/sockjs/sockjs-node/pull/262, build is still failing.

Please fix and publish, thank you.

**Comment by brycekahle** [comment]
I will merge your PR, but there is no need to publish a new package version which doesn't have any functional code changes.

**Comment by daniel-seitz** [comment]
I agree as long as there will be a new version on the horizon. Also good spot about jsdelivr!
Thank you @brycekahle
