### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by daniel-seitz** [sockjs/sockjs-node#269]
Hi Bryce, 

do you have plans for the next patch version? 
It's been about 2.5 years since the last release (and I'm getting security warnings about the old jQuery references)

Daniel

**Comment by brycekahle** [comment]
The outdated jQuery references are strictly in examples, and thus do not affect any actual usage. This library is considered stable and thus doesn't need regular releases. The next release will likely be a transition from CoffeeScript to vanilla JS, but that will be a major version change.

**Comment by daniel-seitz** [comment]
Hi Bryce, I agree with the point that this has no effect. But then, this library contains the examples and all people out there would - should they look into it - receive security warnings. Guess how many hours * developers = waisted time this is on this planet..

This is what patch versions are for, just bump up by one. Maybe even exclude the examples from the library itself. Thats it. 

I was not referring to a next major release nor regular ones, I agree, this does not make sense. But I would like to see the patch being published. We changed the code for this already. 

Why the hesitation?

**Comment by brycekahle** [comment]
I'm not responsible for false positives from security scanners.

The code has been changed, but only in `master` which is where the CoffeeScript to JS transition is taking place. The changes would need to be backported to `v0.3.19`.

Is that something you would want to submit a PR for?

**Comment by daniel-seitz** [comment]
@brycekahle thank you!
I hope you guys get through corona well.
