### ISSUE TITLE
Update websocket-driver Version

### ISSUE THREAD

**Issue by ffjanhoeck** [sockjs/sockjs-node#275]
Hey folks,

could you please verify if you can update the `websocket-driver` version from `0.6.5` to `0.7.4`?
The update is important, because `websocket-driver` has a dependency called `websocket-extension`. This dependency had a security issue which was fixed in version `0.1.4`. But to get that version, you have to update.

The issue was:
```
The ReDoS flaw allows an attacker to exhaust the server's capacity to process
incoming requests by sending a WebSocket handshake request containing a header
of the following form:

Sec-WebSocket-Extensions: a; b="\c\c\c\c\c\c\c\c\c\c ...

That is, a header containing an unclosed string parameter value whose content is
a repeating two-byte sequence of a backslash and some other character. The
parser takes exponential time to reject this header as invalid, and this will
block the processing of any other work on the same thread. Thus if you are
running a single-threaded server, such a request can render your service
completely unavailable.
```

The dependency `faye-websocket` also has the `websocket-driver` dependency.

**Comment by brycekahle** [comment]
Thanks for reporting this. I will take a look and get back to you.

**Comment by brycekahle** [comment]
`0.3.21` is released. Thanks for reporting.
