### ISSUE TITLE
Insecure URL sockjs-node

### ISSUE THREAD

**Issue by rrd108** [sockjs/sockjs-node#277]
Hi,

In a vuejs application when I run lighthouse audit I get the following error:

Insecure url http://192.168.1.2:8080/sockjs-node/info?t=1608572214586

It seems that this (and only this) module do not use the localhost fomain but the equivalent 192.168.1.2 and because of this the audit fails.

npm 6.14.8
sockjs 0.3.20

Is there anything what I can do about this?

**Comment by brycekahle** [comment]
This library attaches to an existing http server, and thus does not control what address it listens on.
