### ISSUE TITLE
Publish patch version to  v0.3 upgrade uuid version 

### ISSUE THREAD

**Issue by bung87** [sockjs/sockjs-node#288]
current depends on "uuid": "^3.4.0" 
uuid latest version is 8.3.2

**Comment by jaqua** [comment]
@bung87  uuid has been updated in June 2020 (https://github.com/sockjs/sockjs-node/commit/da1f106db233b844985e9f9812995fbb0b6b9985#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), but this version marked as 0.4-rc has never been published.

@brycekahle I think this package isn't maintained anymore...

**Comment by dartess** [comment]
Any updates when 0.4 is ready?

**Comment by hailwood** [comment]
@brycekahle While it doesn't appear to break anything, having this output on your npm installs is not nice
![image](https://user-images.githubusercontent.com/709773/141881914-4237a837-875c-4d5e-a7b2-83ad49cd6760.png)

It's going to affect everyone using webpack-dev-server so maybe easier to do the release than hold off for what feels like "it's not a big enough update to justify 1.0?". Especially if as you say the package is in a stable state I'd imagine there won't be any big updates so what is considered a 'compelling reason' if causing a warning for millions of users is not?

**Comment by zdm** [comment]
It's time to release `1.0.0`.

**Comment by zdm** [comment]
Is it hard to release npm package? 
I see, that uuid v8 is already used in the latest code.

**Comment by JanKanty** [comment]
If your changes keep from releasing v1.0.0 maybe we can release v0.3.22 with only `uuid` bumped up?

**Comment by jaqua** [comment]
@JanKanty brycekahle said in his answer he won't do this bump up, as he think this package is in stable state.
But @brycekahle following [semver stable release](https://semver.org/#how-do-i-know-when-to-release-100) should not be 0.3.21. So in my opinion the explanation doesn't fit the needs of the user. Versioning shouldn't be done emotionaly, but just rational.
You also said the package is maintained, but in fact it is not - as many users explained in this thread.
Just my cents... Please don't mind.

**Comment by zdm** [comment]
uuid v8 will make this package more "stable", because it will remove potential issues, found last years (as it described in warnings on install).
really unable to understand why it is impossible to publish it to the npm registry.
by the way, sockjs will be removed from the webpack dev server on next major release.

**Comment by brycekahle** [comment]
> said in his answer he won't do this bump up, as he think this package is in stable state.

@jaqua That isn't *exactly* what I said. I said I don't upgrade things without compelling reasons. As @reporter123 observed, the issue with `Math.random` and thus some `uuid` versions, is that it isn't cryptographically secure. That isn't a concern for the usage of UUIDs in this project, where they are only used for session ids. If someone had opened an issue outlining how they thought the old `uuid` was affecting this project specifically, that would've been a productive conversation towards an upgrade. 

> following [semver stable release](https://semver.org/#how-do-i-know-when-to-release-100) should not be 0.3.21

The thinking on 0.x releases has shifted over time. Node.js itself was 0.x releases for a long time and used in production. React.js was the same.

@zdm Some folks are willing to demand work done by others, but not do the work themselves. I don't see any PRs with this change.

The `main` branch is not ready, as the conversion from coffeescript to javascript is a decent amount of work to verify. If I were to do this, it would be in the form @JanKanty suggested.

**Comment by brycekahle** [comment]
Fixed in `b55d47856efb9b6274578c37feec71e662e9a03e`

**Comment by JanKanty** [comment]
@brycekahle Can I then create new branch from `v0.3.21` tag and fix it and you will publish it? Everybody will be happy :)

**Comment by brycekahle** [comment]
@JanKanty I went ahead and did it.

**Comment by JanKanty** [comment]
@brycekahle you are a diamond <3
