### ISSUE TITLE
uuid reference issue

### ISSUE THREAD

**Issue by ramicohen303** [sockjs/sockjs-node#297]
In a project that depends on sockjs indirectly (I use cypress.io), I get the following error:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/xxxx/node_modules/uuid/package.json

**Comment by ramicohen303** [comment]
This seems to be a result of the release from about an hour ago. Everything was working fine earlier today.

**Comment by brycekahle** [comment]
Thanks for the heads up.

**Comment by ZachFontenot** [comment]
I am also running into this after trying to build a freshly created(around 1pm CST which ran fine) Vue project on my other computer now.

**Comment by JanKanty** [comment]
> In a project that depends on sockjs indirectly (I use cypress.io), I get the following error:
> 
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/xxxx/node_modules/uuid/package.json

Which version of cypress are you using?

**Comment by brycekahle** [comment]
@ramicohen303 is correct, this was an issue with the version 0.3.22 just published

**Comment by brycekahle** [comment]
Should be fixed in https://github.com/sockjs/sockjs-node/commit/5d8842e7c5320ada0f821587dade58024c9a6f29 and `0.3.23`

**Comment by ramicohen303** [comment]
Thank you for the quick resolution. This is fixed with 0.3.23. Thank you for the quick resolution!!!

**Comment by ZachFontenot** [comment]
Lightning fast. Thanks so much!

**Comment by kolmakova** [comment]
Hi! This problem happens for me since yesterday in 0.3.24.
