### ISSUE TITLE
Close event not fired on Heroku

### ISSUE THREAD

**Issue by eralha** [sockjs/sockjs-node#57]
Hello im experimenting with sockjs and when testing on localhost the close event fires and gives all connected users the message that a user just leave. But when i put my app on a online server it doesn´t fire that event!! 

You can check it here.
http://er-u-count.herokuapp.com/

var cons = {};

var sockjs_echo = sockjs.createServer(sockjs_opts);
sockjs_echo.on('connection', function(conn) {
  console.log('connection' + conn);

  //SAY WELCOME
    conn.write("Welcome");
  //NOTIFY OTHER USERS THAT WE HAVE ARRIVED
    broadcastmsg(conn.sesion+" Joined");

```
cons[conn.id] = conn;

conn.on('data', function(message){
    broadcastmsg(conn.sesion+" SAY: "+message);
});

conn.on('close', function() {
    console.log('close ' + conn);
    delete cons[conn.sesion];
    broadcastmsg(conn.sesion+" is leaving");
});
```

});

//HELPERS
function broadcastmsg(msg){
  for(c in cons){
    cons[c].write(msg);
  }
}

Is there any way to see if a connection is still on?

**Comment by hems** [comment]
i'm not sure if "session affinity" on heroku will sort us out, but might help in some cases.

https://blog.heroku.com/archives/2015/4/28/introducing_session_affinity

I'm giving a go today, hopefully will get great results and not many surprises in the future.
